config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  # GET /posts or /posts.json
  def index

    if params[:search]
      @posts = Post.where('title LIKE ?', "%#{params[:search]}%").or(Post.where('content LIKE ?', "%#{params[:search]}%"))
      
      respond_to do |format|
        format.js
      end
    else
      @posts = Post.all
    end

  end 

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @posts = Post.all
    @post = Post.new(post_params)
    respond_to do |format|
        if @post.save
          format.js {render nothing: true} 
        end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    @posts = Post.all.order(updated_at: :desc)
    respond_to do |format|
      if @post.update(post_params)
        format.js {render nothing: true} 
        format.html { redirect_to @post, notice: "Post was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    if @post.destroy
      @posts = Post.all.order(updated_at: :desc)
      respond_to do |format|
        format.js { render nothing: true }
        format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crudapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/bdf4dec60f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_data.html.erb
<% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.content %></td>
      <td><%= link_to 'Show', post , remote: true %></td>
      <td><%= link_to 'Edit', edit_post_path(post), remote: true %></td>
      <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, remote:true %></td>
    </tr>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: false) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_search.html.erb
<div class="float-left">
    <%= form_tag(posts_path, method: "get", remote: true, :class => "form-inline") do  %>
      <%= text_field_tag :search, params[:search], placeholder:"Buscar un Post", :class =>"form-control" %>
      <%= submit_tag "Buscar", class:"btn btn-primary"%>
    <% end %>
</div>

app/views/posts/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/create.js.erb
$("#data").html("<%=escape_javascript render('posts/data', post:@post)%>")
$("#createData").html(" ")

app/views/posts/destroy.js.erb
$("#data").html("<%=escape_javascript render('posts/data', post:@post)%>")

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/edit.js.erb
$("#createData").html("<%=escape_javascript render('posts/form', post:@post)%>")

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div id="createData"></div>
<h1>Posts</h1>

<div class="float-left">
    <%= form_tag(posts_path, method: "get", remote: true, :class => "form-inline") do  %>
      <%= text_field_tag :search, params[:search], placeholder:"Buscar un Post", :class =>"form-control" %>
      <%= submit_tag "Buscar", class:"btn btn-primary"%>
    <% end %>

<br>
<div>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody id="data">
      <%= render('posts/data') %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'New Post', new_post_path, remote: true %>

<div id="showData"></div>

app/views/posts/index.js.erb
$("#data").html("<%=escape_javascript(render partial: 'posts/data', @posts => @posts)%>")

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/new.js.erb
$("#createData").html("<%=escape_javascript render('posts/form', post:@post)%>")

app/views/posts/show.js.erb
$("#showData").html("<%= escape_javascript render('posts/show') %>")

app/views/posts/update.js.erb
$("#data").html("<%=escape_javascript render('posts/data', post:@post)%>")
$("#createData").html(" ")